name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Installing dependencies
        run: yarn install
      - name: Building storybook
        run: yarn build:storybook
      - name: Checking style
        run: yarn test:lint
        if: always()
      - name: Checking types
        run: yarn test:types
        if: always()
      - name: Running unit tests
        run: yarn test:unit
        if: always()
